INSERT INTO USERS VALUES (1, 'admin_1', '$2a$10$aaviGfrIlWFOjVA3of1XUOxS/MgooxaDAp9nSsa5Rg2/rqF07D4IO');
INSERT INTO USERS VALUES (2, 'provider_1', '$2a$10$9tKZLJLxraZviFORfTsGberVEBlc9aKW1//Y4ra6F7iej/kBO9wyG');
INSERT INTO USERS VALUES (3, 'provider_2', '$2a$10$HkeSfUrPlKscXGFEfPgNy.0JAsYbRHYifqSKv3l6tAmAoWVhpA/8e');

INSERT INTO ROLES VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES VALUES (2, 'ROLE_MANUFACTURER');

INSERT INTO USERS_ROLES VALUES (1, 1);
INSERT INTO USERS_ROLES VALUES (2, 2);
INSERT INTO USERS_ROLES VALUES (3, 2);