CREATE TABLE IF NOT EXISTS PROVIDER (
     ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     NAME VARCHAR(50) NULL,
     COUNTRY VARCHAR(50) NULL,
     CREATION_DATE TIMESTAMP NULL,
     CREATED_BY VARCHAR(50) NULL,
     MODIFICATION_DATE TIMESTAMP NULL,
     MODIFIED_BY VARCHAR(50) NULL);

CREATE TABLE IF NOT EXISTS BEERS (
     ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     PROVIDER_ID BIGINT NULL,
     NAME VARCHAR(50) NULL,
     GRADUATION VARCHAR(10) NULL,
     TYPE VARCHAR(10) NULL,
     DESCRIPTION VARCHAR(300) NULL,
     CREATION_DATE TIMESTAMP NULL,
     CREATED_BY VARCHAR(50) NULL,
     MODIFICATION_DATE TIMESTAMP NULL,
     MODIFIED_BY VARCHAR(50) NULL,
     FOREIGN KEY (PROVIDER_ID) references PROVIDER(ID));


COMMIT;